misc/secrets: add multiedit subcommand

diff --git a/misc/secrets b/misc/secrets
--- a/misc/secrets
+++ b/misc/secrets
@@ -159,6 +159,25 @@ inject_commit_and_push_changes() {
     push_to_repo_if_changed
 }
 
+multifind() { local workdir=$1 path=$2
+    # finds $workdir/*/$path files with the same contents
+    candidates=$(find "$workdir"/*/"$path" -maxdepth 1)
+    candidates=$(sort <<<"$candidates")
+    first=$(head -n1 <<<"$candidates")
+    iter=$(tr '\n' ' ' <<<"$candidates")
+    [[ -r "$first" ]]
+    for c in $iter; do
+        [[ -r "$c" ]]
+        if ! cmp -s "$first" "$c"; then
+
+            sha256sum "$workdir"/*/"$path" 1>&2
+            echo 1>&2 "There are differences between */$path! Aborting."
+            exit 1
+        fi
+    done
+    echo "$iter"
+}
+
 ### subcommands
 
 subcmd_init() {
@@ -190,6 +209,24 @@ subcmd_exec() {
     else
         (export PS1='@secrets$ ' HISTSIZE=0; bash --norc)
     fi
+    inject_commit_and_push_changes "${COMMIT_MSG:-}"
+}
+
+subcmd_multiedit() { local path=$1
+    [[ $# == 1 ]]
+    workdir=$(clone_unlock)
+    cd "$workdir"
+
+    find_pre=$(multifind "$workdir" "$path"); [[ -n "$find_pre" ]]
+    first=$(tr ' ' '\n' <<<"$find_pre" | head -n1); [[ -n "$first" ]]
+    "$EDITOR" "$first"
+    for c in $find_pre; do
+        if [[ "$first" != "$c" ]]; then
+            cat "$first" > "$c"
+        fi
+    done
+    find_post=$(multifind "$workdir" "$path")
+    [[ "$find_pre" == "$find_post" ]]
     inject_commit_and_push_changes "${COMMIT_MSG:-}"
 }
 
@@ -326,6 +363,9 @@ case "$subcommand" in
         ;;
     vi)
         COMMIT_MSG="edit $*" subcmd_exec vi "$@"
+        ;;
+    multiedit)
+        COMMIT_MSG="edit */$1" subcmd_multiedit "$1"
         ;;
     generate)
         COMMIT_MSG="generate $*" subcmd_generate "$@"
