misc/secrets: prohibit pushing filenames with whitespace

diff --git a/misc/secrets b/misc/secrets
--- a/misc/secrets
+++ b/misc/secrets
@@ -112,6 +112,10 @@ clone_unlock() {
 
 push_to_repo() {
     check_status
+    if [[ "$(find . -print0 | tr '\0' '#')" =~ [[:space:]] ]]; then
+        echo 1>&2 'whitespace in filenames, aborting!'
+        exit 1
+    fi
     git-crypt lock
     if [[ "$PUSH" != "skip" ]]; then
         echo 1>&2 'pushing repository changes...'
