misc/secrets: support ~/.nix-configs

diff --git a/misc/secrets b/misc/secrets
--- a/misc/secrets
+++ b/misc/secrets
@@ -46,9 +46,11 @@ clone() {
 
 sanity_check_host() { local f=$1
     [[ -d "/etc/nixos/hosts/$f" ]] || \
-        { echo 1>&2 "no such host '$f', aborting!"; exit 1; }
+        [[ -d "$HOME/.nix-configs/hosts/$f" ]] || \
+            { echo 1>&2 "no such host '$f', aborting!"; exit 1; }
     [[ -e "/etc/nixos/hosts/$f/disko.nix" ]] || \
-        { echo 1>&2 "'host $f' is not new enough, aborting!"; exit 1; }
+        [[ -e "$HOME/.nix-configs/hosts/$f/disko.nix" ]] || \
+            { echo 1>&2 "'host $f' is not new enough, aborting!"; exit 1; }
 }
 
 find_hosts() {
@@ -318,7 +320,7 @@ subcmd_generate() { local host=$1 type=$2
             dasel put -f misc/pubkeys/nebula.toml -t string "$host" -v "$pub"
             echo 1>&2 -n "add something like \`$host = "
             echo 1>&2 "{ int = \"$int_ip\"; ext = [\"...\"]; };\`"
-            echo 1>&2 'to /etc/nixos/nixos/services/nebula/default.nix'
+            echo 1>&2 'to nixos/services/nebula/default.nix'
             echo 1>&2 'and import ../../nixos/services/nebula'
         ;;
         syncthing)
@@ -331,6 +333,7 @@ subcmd_generate() { local host=$1 type=$2
             pushd "$keydir" > /dev/null
             tar cf "$workdir/$host/@storage/syncthing" key.pem cert.pem
             rm config.xml key.pem cert.pem
+            rm -f .syncthing.tmp.*
             popd > /dev/null
             rm -d "$keydir"
             dasel put -f misc/pubkeys/syncthing.toml \
